baseurl = "https://tectalks.com/"
title = "Tectalks"
author = "Vibin Kurusingal"
canonifyurls = true
languagecode = "en"
theme = "zen"
copyright = "Â© 2026 Tectalks"
# googleAnalytics = "UA-147956139-1"
gtm_id = "GTM-PPC3LG2"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Techtalks"
  logoWidth = 200
  disableWebFonts = false
  poweredby = false
  submitted= true
  feedlinks = false
  cookieConsent= true
  favicon= "apple-touch-icon.png"
#  sidebar= true

[[menu.main]]
    name = "About"
    url  = "/about"

[[menu.main]]
    name = "Instagram"
    url  = "https://instagram.com/vibin.aero"
